In [1]:
from qiskit import quantum_info as qi
import numpy as np
import pandas as pd
pd.options.display.float_format = '{:,.1f}'.format

In [2]:
def I0(L):
    label = ""
    for i in range(0,L):
        label += "I"
    return qi.Operator.from_label(label).data

def Sx(l,L):
    label = ""
    for i in range(0,l):
        label += "I"
    label += "X"
    for i in range(l+1,L):
        label += "I"
    return qi.Operator.from_label(label).data

def Sy(l,L):
    label = ""
    for i in range(0,l):
        label += "I"
    label += "Y"
    for i in range(l+1,L):
        label += "I"
    return qi.Operator.from_label(label).data

def Sz(l,L):
    label = ""
    for i in range(0,l):
        label += "I"
    label += "Z"
    for i in range(l+1,L):
        label += "I"
    return qi.Operator.from_label(label).data
    
def Sp(l,L):
    return Sx(0,L)+Sy(0,L)

def Sm(l,L):
    return Sx(0,L)-Sy(0,L)

In [3]:
def H(Jx,Jy,Jz,L):
    h=0
    for i in range(0,L-1):
        h+= Jx*np.dot(Sz(i,L),Sz(i+1,L))
        h+= Jy*np.dot(Sx(i,L),Sx(i+1,L))
        h+= Jz*np.dot(Sy(i,L),Sy(i+1,L))
    h+= Jx*np.dot(Sz(L-1,L),Sz(0,L))
    h+= Jy*np.dot(Sx(L-1,L),Sx(0,L))
    h+= Jz*np.dot(Sy(L-1,L),Sy(0,L))
    return h
        

In [4]:
H(1,1,1,2)

array([[ 2.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j, -2.+0.j,  4.+0.j,  0.+0.j],
       [ 0.+0.j,  4.+0.j, -2.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  2.+0.j]])

In [5]:
pd.DataFrame(Sz(2,3))

0         1        2         3        4         5        6         7
0 1.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
1 0.0+0.0j -1.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
2 0.0+0.0j  0.0+0.0j 1.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
3 0.0+0.0j  0.0+0.0j 0.0+0.0j -1.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
4 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 1.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j
5 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j -1.0+0.0j 0.0+0.0j  0.0+0.0j
6 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 1.0+0.0j  0.0+0.0j
7 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j  0.0+0.0j 0.0+0.0j -1.0+0.0j

In [6]:
pd.DataFrame(Sz(0,3))

0        1        2        3         4         5         6         7
0 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
1 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
2 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
4 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j

In [7]:
pd.DataFrame(Sx(0,3))

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j
4 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [8]:
these = 1/2*(I0(3)-np.dot(Sz(0,3),Sz(2,3)))
pd.DataFrame(these)

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
4 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [9]:
flip = np.dot(Sx(0,3),Sx(2,3))
pd.DataFrame(flip)

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
4 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [10]:
swap = np.dot(flip,these)
pd.DataFrame(swap)

0        1        2        3        4        5        6        7
0 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
4 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j

In [11]:
keep = 1/2*(I0(3)+np.dot(Sz(0,3),Sz(2,3)))
pd.DataFrame(keep+swap)

0        1        2        3        4        5        6        7
0 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
1 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
2 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
3 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j
4 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
5 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j
6 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j
7 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 0.0+0.0j 1.0+0.0j

In [12]:
def Exchange(i,j,L):
    change = 1/2*(I0(L)-np.dot(Sz(i,L),Sz(j,L)))
    keep = 1/2*(I0(L)+np.dot(Sz(i,L),Sz(j,L)))
    flip = np.dot(Sx(i,L),Sx(j,L))
    swap = np.dot(flip,change)
    return keep+swap
    

In [13]:
#Translation Operator
def T(L):
    t = I0(L)
    for i in range(0,L-1):
        exc = Exchange(L-2-i,L-1-i,L)
        t = np.dot(exc,t)
    return t

### Below I do a bunch of tests of the translation operator

In [14]:
pd.DataFrame(H(1,1,1,3))

0         1         2         3         4         5         6  \
0 3.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
1 0.0+0.0j -1.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
2 0.0+0.0j  2.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
3 0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  2.0+0.0j   
4 0.0+0.0j  2.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j   
5 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  2.0+0.0j   
6 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j -1.0+0.0j   
7 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   

         7  
0 0.0+0.0j  
1 0.0+0.0j  
2 0.0+0.0j  
3 0.0+0.0j  
4 0.0+0.0j  
5 0.0+0.0j  
6 0.0+0.0j  
7 3.0+0.0j

In [15]:
pd.DataFrame(np.dot(T(3),np.dot(H(1,1,1,3),np.transpose(T(3)))))

0         1         2         3         4         5         6  \
0 3.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   
1 0.0+0.0j -1.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
2 0.0+0.0j  2.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  0.0+0.0j   
3 0.0+0.0j  0.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  2.0+0.0j  2.0+0.0j   
4 0.0+0.0j  2.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  0.0+0.0j  0.0+0.0j   
5 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j -1.0+0.0j  2.0+0.0j   
6 0.0+0.0j  0.0+0.0j  0.0+0.0j  2.0+0.0j  0.0+0.0j  2.0+0.0j -1.0+0.0j   
7 0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j  0.0+0.0j   

         7  
0 0.0+0.0j  
1 0.0+0.0j  
2 0.0+0.0j  
3 0.0+0.0j  
4 0.0+0.0j  
5 0.0+0.0j  
6 0.0+0.0j  
7 3.0+0.0j

In [16]:
H(1,1,1,3)-np.dot(T(3),np.dot(H(1,1,1,3),np.transpose(T(3))))

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [17]:
np.dot(T(3),np.array([111,112,121,122,211,212,221,222]))

array([111.+0.j, 121.+0.j, 211.+0.j, 221.+0.j, 112.+0.j, 122.+0.j,
       212.+0.j, 222.+0.j])

In [18]:
np.dot(np.dot(T(3),Sz(0,3)),np.transpose(T(3)))-Sz(1,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [19]:
np.dot(np.dot(T(3),Sz(1,3)),np.transpose(T(3)))-Sz(2,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [20]:
np.dot(np.dot(T(3),Sz(2,3)),np.transpose(T(3)))-Sz(0,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [21]:
np.dot(np.dot(T(3),Sx(0,3)),np.transpose(T(3)))-Sx(1,3)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [22]:
np.dot(T(3),np.dot(T(3),T(3)))

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [23]:
np.dot(T(3),H(1,1,1,3))-np.dot(H(1,1,1,3),T(3))

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

### Now let us take a look at constructing eigenstates of T

In [79]:
psi_a = qi.Statevector.from_label("000").data
psi_b = qi.Statevector.from_label("100").data
psi_c = qi.Statevector.from_label("110").data
psi_d = qi.Statevector.from_label("111").data

In [80]:
def psi_k(psi,m,L):
    k = m*2*np.pi/(L)
    psi_l = [psi]
    for r in range(1,L):
        psi_l.append(np.exp(-1j*k)*np.dot(T(L),psi_l[r-1])) 
    return sum(psi_l)

In [85]:
m=1
L=3
psi = psi_d
np.exp(-1j*m*2*np.pi/(L))*np.dot(T(3),psi_k(psi,m,L))-psi_k(psi,m,L)

array([ 0.00000000e+00-0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
        0.00000000e+00-0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
        0.00000000e+00-0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
        0.00000000e+00-0.00000000e+00j, -1.21910949e-16+5.95748495e-16j])

In [86]:
def bkt(psi_a,psi_b):
    return np.dot(np.conjugate(psi_a),psi_b)

In [110]:
k = m*2*np.pi/(L)
psi_l = [psi_a]
for r in range(1,L):
    psi_l.append(np.exp(-1j*k)*np.dot(T(L),psi_l[r-1])) 
sum(psi_l)
psi_l[0]+psi_l[1]+psi_l[2]

array([-1.11022302e-16-3.33066907e-16j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j])

In [102]:
print( bkt(psi_k(psi_a,1,3),psi_k(psi_a,1,3)) ) 

(1.232595164407831e-31+0j)


In [101]:
print( bkt(psi_k(psi_b,-1,3),psi_k(psi_b,1,3)) ) 
print( bkt(psi_k(psi_b,0,3),psi_k(psi_b,1,3)) ) 
print( bkt(psi_k(psi_a,1,3),psi_k(psi_b,1,3)) ) 
print( bkt(psi_k(psi_c,1,3),psi_k(psi_b,1,3)) )
print( bkt(psi_k(psi_c,-1,3),psi_k(psi_c,1,3)) )
print( bkt(psi_k(psi_c,0,3),psi_k(psi_c,1,3)) )
print( bkt(psi_k(psi_d,1,3),psi_k(psi_b,1,3)) ) 
print( bkt(psi_k(psi_d,1,3),psi_k(psi_c,-1,3)) ) 
print( bkt(psi_k(psi_d,1,3),psi_k(psi_d,0,3)) ) 
print( bkt(psi_k(psi_d,1,3),psi_k(psi_d,-1,3)) ) 

(4.440892098500626e-16-5.551115123125783e-16j)
(-1.1102230246251565e-16-3.3306690738754696e-16j)
0j
0j
(4.440892098500626e-16-5.551115123125783e-16j)
-3.3306690738754696e-16j
0j
0j
(-3.3306690738754696e-16+9.992007221626409e-16j)
(-9.860761315262648e-32-7.395570986446986e-32j)
(1.232595164407831e-31+0j)


There is a state for each occupancy number.  

In [1]:
pwd

'C:\\Users\\jsten\\IBMQ\\Explorations'